language: rust

cache: cargo

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libssl-dev; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install openssl; fi
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install openssl; fi

os:
  - linux
  - osx
  - windows

script:
  - cargo build --verbose
  - cargo test ipv4 --verbose -- --test-threads=1

