language: rust

addons:
  apt:
    packages:
      - libssl-dev
  homebrew:
    packages:
      - openssl
    update: true

install:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install openssl; fi

os:
  - linux
  - osx
  - windows

script:
  - cargo test ipv4 --verbose -- --test-threads=1

